# =============================================================================
# Module 3 - Main Application
# =============================================================================

from flask import Flask, render_template
from Mod_1_API import gather_tweets
from Mod_2_DataAnalysis import draw_graph, delete_plots, compare_tweets, word_cloud, sentiment_graphs

app = Flask(__name__)

@app.route("/")

def homepage():
    """
    Renders the html file with the information generated by functions in
    Module 1 and 2. Employs Jinja2 commands to make the interface.
    
    Parameters
    ----------
    No parameters required.
    
    Returns
    -------
    Returns data frames and barplots to the html code.
    
    """
    delete_plots()
    name_plot = draw_graph(10)
    name_word_cloud = word_cloud()
    sentiment_analysis1 = sentiment_graphs("Politifact")
    sentiment_analysis2 = sentiment_graphs("factcheckdotorg")
    sentiment_analysis3 = sentiment_graphs("snopes")
        
    tweets = gather_tweets(n=10, df=False)
    return render_template("home.html", 
                           tweets = tweets, 
                           name_plot = name_plot,
                           name_word_cloud = name_word_cloud, 
                           sentiment_analysis1 = sentiment_analysis1,
                           sentiment_analysis2 = sentiment_analysis2,
                           sentiment_analysis3 = sentiment_analysis3)


if __name__ == "__main__":
    app.run()
